import '../styles/globals.css'
import Head from 'next/head'
import { Toaster } from 'react-hot-toast'
function MyApp({ Component, pageProps }) {
  return (
  <>
   <Head>
        <title>Ceejs Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toaster />
      <Component {...pageProps} />
      </>
  )
}

export default MyApp
